services:  
  web:  
    build: .  
    ports:  
      - "8000:8000"  
    depends_on:  
      - db  
      - redis  

  db:  
    image: postgres:latest  
    environment:  
      POSTGRES_USER: user  
      POSTGRES_PASSWORD: password  
      POSTGRES_DB: dbname  
    ports:  
      - "5432:5432"  

  redis:  
    image: redis:latest  
    ports:  
      - "6379:6379"